import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrainCircuit,GitBranch,Search,Code2,Play,ArrowUpRight,Activity,BookOpen,Download,Square,ChevronRight,RefreshCw,CheckCircle2,AlertCircle} from 'lucide-react';
import {api} from './api';
import Graph from './components/Graph';
import {CodeEditor,CodeDiff} from './editor/CodeEditor';
import Workflow from './pages/Workflow';
import './style.css';

type RecordData=Record<string,any>;
function App(){
 const [health,setHealth]=useState<RecordData|null>(null),[repos,setRepos]=useState<RecordData[]>([]),[repo,setRepo]=useState<RecordData|null>(null);
 const [tab,setTab]=useState('overview'),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [graph,setGraph]=useState<any>(null),[files,setFiles]=useState<string[]>([]),[selected,setSelected]=useState(''),[content,setContent]=useState('');
 const [query,setQuery]=useState(''),[results,setResults]=useState<RecordData|null>(null),[mode,setMode]=useState('hybrid');
 const [issue,setIssue]=useState('Percentage discounts produce the wrong checkout total.'),[profile,setProfile]=useState('pytest'),[task,setTask]=useState<RecordData|null>(null),[tasks,setTasks]=useState<RecordData[]>([]);
 const [gitOutput,setGitOutput]=useState(''),[diffOriginal,setDiffOriginal]=useState(''),[diffPath,setDiffPath]=useState('');
 const run=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const refresh=async()=>{const [h,r,t]=await Promise.all([api('/health'),api('/repos'),api('/tasks')]);setHealth(h);setRepos(r);setTasks(t)};
 useEffect(()=>{void run(refresh)},[]);
 useEffect(()=>{if(!repo||!['queued','indexing'].includes(repo.status))return;const timer=setInterval(()=>{api('/repos/'+repo.id).then(r=>{setRepo(r);if(r.status==='ready')void refresh()}).catch(e=>setError(e.message))},1500);return()=>clearInterval(timer)},[repo?.id,repo?.status]);
 useEffect(()=>{setGraph(null);setFiles([]);setSelected('');setResults(null);if(repo?.status==='ready'){Promise.all([api(`/repos/${repo.id}/graph`),api(`/repos/${repo.id}/files`)]).then(([g,f])=>{setGraph(g);setFiles(f)}).catch(e=>setError(e.message))}},[repo?.id,repo?.status]);
 useEffect(()=>{if(!task||!['queued','running'].includes(task.status))return;const timer=setInterval(()=>{api('/tasks/'+task.id).then(t=>{setTask(t);if(!['queued','running'].includes(t.status))void refresh()}).catch(e=>setError(e.message))},1200);return()=>clearInterval(timer)},[task?.id,task?.status]);
 const openFile=async(path:string)=>{const r=await api(`/repos/${repo!.id}/file?path=${encodeURIComponent(path)}`);setSelected(path);setContent(r.content);setGitOutput('');setTab('code')};
 const importRepo=(demo=false)=>run(async()=>{const r=await api(demo?'/demo':'/repos',demo?{}:{url});setRepo(r);setTask(null);setTab('overview');await refresh()});
 const startTask=(demo=false)=>run(async()=>{const t=await api('/tasks',{repo_id:repo!.id,issue,profile,demo});setTask(t);setTab('repair');await refresh()});
 const latest=task?.attempts?.at(-1);
 useEffect(()=>{setDiffPath('');setDiffOriginal('');const path=Object.keys(latest?.changes||{})[0];if(path&&task){setDiffPath(path);api(`/repos/${task.repo_id}/file?path=${encodeURIComponent(path)}`).then(r=>setDiffOriginal(r.content)).catch(e=>setError(e.message))}},[task?.id,task?.attempts?.length]);
 return <div className="layout"><aside className="sidebar"><a className="brand" href="/"><div className="brand-icon"><BrainCircuit size={23}/></div>CodeMind<span>LAB</span></a><div className="workspace-label">YOUR WORKSPACE</div><nav>{[['overview','Repository',GitBranch],['code','Code explorer',Code2],['search','Search & retrieve',Search],['repair','Repair studio',Activity],['guide','How it works',BookOpen]].map(([key,label,Icon]:any)=><button key={key} className={tab===key?'nav active':'nav'} onClick={()=>setTab(key)}><Icon size={18}/>{label}{tab===key&&<ChevronRight size={14}/>}</button>)}</nav><div className="repo-list"><div className="workspace-label">REPOSITORIES <span>{repos.length}</span></div>{repos.map(r=><button key={r.id} className={repo?.id===r.id?'repo-link chosen':'repo-link'} onClick={()=>{setRepo(r);setTask(null);setTab('overview')}}><span className={'dot '+(r.status==='ready'?'green':'')}/><span>{r.name}</span></button>)}</div><div className="sidebar-foot"><div><span className={'dot '+(health?.llm.configured?'green':'')}/>Groq {health?.llm.configured?'connected':'key needed'}</div><div><span className={'dot '+(health?.sandbox.available?'green':'')}/>Sandbox {health?.sandbox.available?'ready':'offline'}</div><small>Local workspace · v0.1</small></div></aside>
 <main><header><div className="breadcrumbs">Workspace <ChevronRight size={13}/> <strong>{repo?.name||'Start exploring'}</strong></div><button className="icon-button" title="Refresh status" onClick={()=>void run(refresh)}><RefreshCw size={16}/></button><span className="local-badge">LOCAL FIRST</span></header><div className="main-content">
 {error&&<div role="alert" className="error"><AlertCircle size={18}/>{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
 {tab==='overview'&&<><div className="title-row"><div><div className="eyebrow">REPOSITORY INTELLIGENCE</div><h1>Understand the code.<br/><span>Prove the fix.</span></h1><p className="intro">Explore architecture, trace the evidence, and test every change.</p></div><div className="hero-mark"><BrainCircuit size={76} strokeWidth={1}/></div></div><section className="panel import-panel"><div><h3>Bring a repository</h3><p className="muted">Public GitHub repositories. A separate snapshot keeps your source untouched.</p></div><form onSubmit={e=>{e.preventDefault();void importRepo()}}><GitBranch size={18}/><input aria-label="GitHub repository URL" placeholder="https://github.com/owner/repository" value={url} onChange={e=>setUrl(e.target.value)} required/><button className="primary" disabled={busy||!url}>Analyze repository <ArrowUpRight size={16}/></button></form><div className="demo-row"><span>Want to see the complete workflow?</span><button disabled={busy} onClick={()=>void importRepo(true)}>Load the discount-service demo <ChevronRight size={14}/></button></div></section>
 {!repo&&<div className="feature-grid">{[[GitBranch,'Architecture, extracted','Functions, imports and call relationships from the source.'],[Search,'Context, connected','Keyword matches, graph neighbors and optional semantic search.'],[CheckCircle2,'Results, earned','A failing baseline, isolated tests and an explicit verdict.']].map(([Icon,title,body]:any)=><section className="panel feature" key={title}><Icon size={22}/><h3>{title}</h3><p>{body}</p></section>)}</div>}
 {repo&&repo.status!=='ready'&&<section className="panel"><h3>{repo.status==='error'?'Analysis stopped':'Repository '+repo.status}</h3><p className="muted">{repo.error||'Cloning and building the code index…'}</p></section>}
 {repo?.status==='ready'&&<><div className="stats">{[[repo.summary.file_count,'Source files'],[repo.summary.symbol_count,'Symbols'],[graph?.edges.length||0,'Relationships'],[repo.summary.chunk_count,'Search chunks']].map(([n,l])=><div className="stat" key={l}><span>{l}</span><strong>{n}</strong></div>)}</div><section className="panel"><div className="section-title"><h2>Architecture map</h2><span className="pill">{Object.keys(repo.summary.languages).join(' · ')}</span></div>{graph&&<Graph graph={graph} onOpen={p=>void run(()=>openFile(p))}/>}<p className="muted">{graph?.limitations}</p><div className="tags">{repo.summary.frameworks.map((f:string)=><span className="pill" key={f}>{f}</span>)}</div>{repo.summary.omitted_count>0&&<p className="muted">{repo.summary.omitted_count} files excluded by size, type or privacy filters.</p>}{repo.parse_errors?.length>0&&<details><summary>Parser warnings ({repo.parse_errors.length})</summary><pre>{repo.parse_errors.join('\n')}</pre></details>}</section><section className="panel"><h3>Recent changes</h3>{repo.history?.map((h:any)=><button className="commit" key={h.commit} onClick={()=>void run(async()=>setGitOutput((await api(`/repos/${repo.id}/git?commit=${h.commit}`)).output))}><code>{h.commit}</code><span>{h.subject}</span><small>{h.date}</small></button>)}{gitOutput&&<pre className="log">{gitOutput}</pre>}</section></>}
 </>}
 {tab==='code'&&<><PageTitle title="Code explorer" sub="Read the exact source used by the analysis."/>{repo?.status==='ready'?<section className="panel explorer"><div className="file-tree">{files.map(f=><button key={f} className={selected===f?'selected':''} onClick={()=>void run(()=>openFile(f))}>{f}</button>)}</div><div className="editor-pane"><div className="editor-heading"><code>{selected||'Select a file'}</code>{selected&&<button onClick={()=>void run(async()=>setGitOutput((await api(`/repos/${repo.id}/git?path=${encodeURIComponent(selected)}`)).output))}>Git blame</button>}</div><CodeEditor path={selected||'empty.txt'} content={content}/>{gitOutput&&<pre className="log">{gitOutput}</pre>}</div></section>:<Empty/>}</>}
 {tab==='search'&&<><PageTitle title="Search across the system" sub="Find code by meaning, identifiers and connected modules."/>{repo?.status==='ready'?<><form className="panel search-form" onSubmit={e=>{e.preventDefault();void run(async()=>setResults(await api(`/repos/${repo.id}/search`,{query,mode})))}}><input aria-label="Search query" placeholder="Where is the discount calculated?" value={query} onChange={e=>setQuery(e.target.value)} required/><select aria-label="Retrieval mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="hybrid">Hybrid</option><option value="keyword">BM25 only</option><option value="semantic">Semantic only</option></select><button className="primary" disabled={busy}>Search</button></form>{results&&<><div className="notice">{results.semantic_enabled?'Semantic embeddings enabled.':'Semantic embeddings are disabled. Hybrid currently combines BM25 and graph neighbors; semantic-only returns no results.'}</div>{results.semantic_error&&<p className="error">{results.semantic_error}</p>}{results.results.map((r:any)=><button className="panel result" key={r.id} onClick={()=>void run(()=>openFile(r.path))}><div><code>{r.path}:{r.line}–{r.end}</code><span className="pill">{r.via.join(' + ')}</span></div><pre>{r.text.slice(0,900)}</pre></button>)}{!results.results.length&&<p className="muted">No matches. Try an identifier, or enable semantic embeddings.</p>}</>}</>:<Empty/>}</>}
 {tab==='repair'&&<><PageTitle title="Repair studio" sub="An inspectable path from bug report to tested patch."/>{repo?.status==='ready'?<><section className="panel"><label className="field-label" htmlFor="issue">What should CodeMind investigate?</label><textarea id="issue" value={issue} onChange={e=>setIssue(e.target.value)} rows={3}/><div className="form-actions"><select aria-label="Test profile" value={profile} onChange={e=>setProfile(e.target.value)}><option value="pytest">Python · pytest</option><option value="node-test">JavaScript · node --test</option></select><button className="primary" disabled={busy||!health?.llm.configured||issue.length<8} onClick={()=>void startTask()}><Play size={15}/>Investigate with Groq</button>{repo.demo&&<button disabled={busy} onClick={()=>void startTask(true)}>Run scripted demo</button>}</div>{!health?.llm.configured&&<p className="muted">Set GROQ_API_KEY in your local .env and restart to enable AI tasks.</p>}{!health?.sandbox.available&&<div className="notice">{health?.sandbox.reason}. Patches can be generated, but will remain unverified.</div>}</section>
 {task&&<><div className="section-title"><h2>{task.demo?'Scripted demo':'Investigation'} <span className="pill">{task.status}</span></h2>{['queued','running'].includes(task.status)&&<button onClick={()=>void run(async()=>setTask(await api(`/tasks/${task.id}/cancel`,{})))}><Square size={14}/>Cancel</button>}</div>{task.error&&<div className="error">{task.error}</div>}{task.result&&<div className={'verdict '+task.result.verdict}><CheckCircle2 size={22}/><div><strong>{task.result.verdict.replaceAll('_',' ').toUpperCase()}</strong><p>{task.result.reason}</p></div></div>}
 <div className="task-grid"><section className="panel timeline"><h3>Evidence trail</h3>{task.events?.map((event:any)=><details key={event.seq}><summary><span className="dot green"/>{event.stage}<small>{new Date(event.time).toLocaleTimeString()}</small></summary><pre>{JSON.stringify(event.data,null,2)}</pre></details>)}{!task.events?.length&&<p className="muted">Waiting for the worker…</p>}</section><section className="panel"><h3>Test evidence</h3>{[['Baseline',task.baseline],['Latest candidate',latest?.tests]].map(([label,result]:any)=><div className="test-summary" key={label}><h4>{label}<span className="pill">{result?.status||'pending'}</span></h4>{result?.counts&&<p><b>{result.counts.passed}</b> passed · <b>{result.counts.failed}</b> failed · {result.counts.error} errors · {result.counts.skipped} skipped</p>}{result?.reason&&<p className="muted">{result.reason}</p>}{result?.tests?.map((t:any)=><div className="test-case" key={t.name}><span className={t.status==='passed'?'success':'muted'}>{t.status}</span><code>{t.name}</code></div>)}{result?.output&&<details><summary>Test output</summary><pre className="log">{result.output}</pre></details>}</div>)}</section></div>
 {latest&&<section className="panel"><div className="section-title"><h3>Proposed changes · attempt {latest.attempt}</h3><a className="button" href={`/api/tasks/${task.id}/patch`} download><Download size={15}/>Download patch</a></div><p className="muted">{latest.explanation} Changes are in a task snapshot; the imported repository is unchanged.</p><select aria-label="Changed file" value={diffPath} onChange={e=>{const p=e.target.value;setDiffPath(p);void run(async()=>setDiffOriginal((await api(`/repos/${task.repo_id}/file?path=${encodeURIComponent(p)}`)).content))}}>{Object.keys(latest.changes).map(p=><option key={p}>{p}</option>)}</select>{diffPath&&<CodeDiff original={diffOriginal} modified={latest.changes[diffPath]||''}/>}</section>}</>}
 <section className="panel"><h3>Task memory</h3>{tasks.filter(t=>t.repo_id===repo.id).map(t=><button className="commit" key={t.id} onClick={()=>void run(async()=>setTask(await api('/tasks/'+t.id)))}><span>{t.issue}</span><span className="pill">{t.result?.verdict||t.status}</span></button>)}{!tasks.some(t=>t.repo_id===repo.id)&&<p className="muted">Your investigations will be saved here.</p>}</section></>:<Empty/>}</>}
 {tab==='guide'&&<Workflow/>}<footer>CodeMind / Repository intelligence lab <span>Evidence over assumptions.</span></footer></div></main></div>
}
function PageTitle({title,sub}:{title:string;sub:string}){return <div className="page-title"><div className="eyebrow">CODEMIND WORKSPACE</div><h1>{title}</h1><p className="intro">{sub}</p></div>}
function Empty(){return <section className="panel empty"><GitBranch size={32}/><h3>No repository selected</h3><p className="muted">Open Repository to import a GitHub project or load the demo.</p></section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
