const {chromium}=require(process.env.PLAYWRIGHT_MODULE || '../frontend/node_modules/playwright');
const fs=require('fs');
(async()=>{
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8000');
await page.getByRole('heading',{name:/Understand the code/}).waitFor();
await page.screenshot({path:'artifacts/home.png',fullPage:true});
await page.getByRole('button',{name:/Load the discount-service demo/}).click();
await page.getByRole('heading',{name:'Architecture map'}).waitFor({timeout:30000});
await page.screenshot({path:'artifacts/repository.png',fullPage:true});
await page.getByRole('button',{name:'Code explorer',exact:true}).click();
await page.getByRole('button',{name:'pricing.py',exact:true}).click();
await page.locator('.monaco-editor').first().waitFor();
await page.getByRole('button',{name:'Search & retrieve',exact:true}).click();
await page.getByRole('textbox',{name:'Search query'}).fill('discount percentage');
await page.getByRole('button',{name:'Search',exact:true}).click();
await page.locator('.result').first().waitFor();
await page.getByRole('button',{name:'Repair studio',exact:true}).click();
await page.getByRole('button',{name:'Run scripted demo',exact:true}).click();
await page.locator('.verdict').waitFor({timeout:30000});
await page.screenshot({path:'artifacts/repair.png',fullPage:true});
const verdict=await page.locator('.verdict').innerText();
const download=await page.getByRole('link',{name:'Download patch'}).getAttribute('href');
const patch=await (await page.request.get('http://127.0.0.1:8000'+download)).text();
if(!patch.includes('subtotal *'))throw Error('Missing patch');
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Repository',exact:true}).click();
await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
fs.writeFileSync('artifacts/browser-check.json',JSON.stringify({errors,verdict,patchDownloaded:true},null,2));
console.log(JSON.stringify({errors,verdict,patchDownloaded:true}));
await browser.close();
if(errors.length)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
